### ISSUE TITLE
Route Position Bearing: APB waypoint ID does not change

### ISSUE THREAD

**Issue by marcobergman** [seandepagnier/autopilot_route_pi#10]
Currently the destination waypoint id in the APB messages seem to be set to empty. This disables waypoint notifications at raymarine autopilots. I'd like to be able to switch the destination waypoint id's on, possibly by some config file setting. 

(btw I also tweaked my pypilot so it maintains heading at waypoint arrival until confirmed - based on changing waypoint id, consistent with raymarine)

Raspberry Pi 4 version 10 buster
OpenCPN 5.2.4
autopilot_route_pi-0.4.0.17-raspbian-armhf-10-buster-armhf/ from cloudsmith.io
also happens when compiled from source
testing method: https://github.com/marcobergman/ais_simulation

**Comment by rgleason** [comment]
Do you have a screenshot that explains this.  Is it still happening? If not, it can be closed.

**Comment by marcobergman** [comment]
It is still happening, and it can be seen as a minor thing: 

![image](https://user-images.githubusercontent.com/17980560/214141452-5b0c7583-8f4b-4f76-b2a6-8ce175efe1ce.png)
