### ISSUE TITLE
Advance Waypoint and Activate Waypoint missing

### ISSUE THREAD

**Issue by marcobergman** [seandepagnier/autopilot_route_pi#11]
Waypoint Bearing and standard XTE: Advance Waypoint and Activate Waypoint are not available anymore in the context menu. That is unhandy. Please maintain this functionality in this current plugin. And for bonus: a keyboard shortcut for Advance Waypoint would be brilliant.

**Comment by rgleason** [comment]
These are available now, but please refer to the testing done here in Windows11  https://github.com/seandepagnier/autopilot_route_pi/issues/26

These functions appear to get frozen and don't work.

**Comment by rgleason** [comment]
Marco, I think this is old and should be closed. You are the only one other than Sean who can close it.

**Comment by rgleason** [comment]
Marco, can you confirm my recent posts about Issues?  If so, please add  a comment and say what OS and version.

**Comment by marcobergman** [comment]
These options that _are_ present in the stock Route Console are _not_ present in the autopilot-route plugin. This could be construed as 'feature request'.

![image](https://user-images.githubusercontent.com/17980560/214137776-8d32753c-20d0-4476-8a38-f1d8e0050e6d.png)
