### ISSUE TITLE
Undock context menu item non-functional

### ISSUE THREAD

**Issue by marcobergman** [seandepagnier/autopilot_route_pi#18]
Both on Windows and *nix this menu item does not seem to have any effect.

**Comment by seandepagnier** [comment]
it works, but you have to dock the console canvas first

**Comment by marcobergman** [comment]
I cannot find out how to dock. That functionality seems to be unavailable in both linux and windows ports.

**Comment by seandepagnier** [comment]
it docks fine but if its not docked the undock does nothing
