### ISSUE TITLE
 Occasional bearing calculation errors, negative values. PIM Master 0.4.7.0 MacOS 10.14.6 #10 

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/autopilot_route_pi#23]
Sean, 
Dave Wright has been doing some good testing of the newly released Autopilot_route_pi version 0.4.7.0  with MacOS.
I hope I have managed to get your current code right!  I have made a PR back to your repository.

I am wondering if you have noticed these errors on your OS?

**Comment by seandepagnier** [comment]
Disable plugin in macosx then until we can verify it is working on that platform.   I have no way to test.

**Comment by rgleason** [comment]
I wrote Dave Wright and hope he will join us and help test. I am closing this.
